// Embedded image assets. Ported from the Electron build's resources/ folder; the
// glyphs themselves are generated by scripts/gen-tray-icons.mjs and unchanged.
package assets

import _ "embed"

// TrayTemplate is the menu-bar glyph for the idle state. It is a TEMPLATE image:
// macOS tints it, so it stays legible in a light or a dark menu bar.
//
//go:embed icons/trayTemplate.png
var TrayTemplate []byte

// TrayActive is the recording state. Deliberately NOT a template image — macOS
// would tint away the red that is the whole point of it.
//
//go:embed icons/trayActive.png
var TrayActive []byte

// AppIcon is the Dock/about icon.
//
//go:embed icons/icon.png
var AppIcon []byte
